spring:
    profiles:
        active: dev


############################################################
#
# mybatis 配置
#
############################################################
mybatis:
    type-aliases-package: cn.bravedawn.pojo        # 所有POJO类所在包路径
    mapper-locations: classpath:mapper/*.xml       # mapper映射文件
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启Mybatis SQL日志打印设置


############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
    mappers: cn.bravedawn.my.mapper.MyMapper
    not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
    identity: MYSQL
# 分页插件配置
pagehelper:
    helperDialect: mysql                   # 配置方言
    supportMethodsArguments: true          # 分页是否支持传递方法参数